steps:
  # build app
  - name: 'gcr.io/cloud-builders/docker'
    id: BuildApp
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/back-end-$_ENV:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/back-end-$_ENV:latest'
      - '--build-arg'
      - 'MONGO_URL=$_MONGO_URL'
      - '--build-arg'
      - 'SERVICE_PORT=$_SERVICE_PORT'
      - '--build-arg'
      - 'YELP_API_KEY=$_YELP_API_KEY'
      - '.'
  # push app
  - name: 'gcr.io/cloud-builders/docker'
    id: PushApp
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/back-end-$_ENV:$SHORT_SHA'
  # run gke-deploy
  - name: 'gcr.io/cloud-builders/gke-deploy:stable'
    args:
      - 'run'
      - '--filename=deploy/manifests/$_ENV/app.yaml'
      - '--image=gcr.io/$PROJECT_ID/back-end-$_ENV:$SHORT_SHA'
      - '--location=$_LOCATION'
      - '--cluster=$_CLUSTER'
images:
  - 'gcr.io/$PROJECT_ID/back-end-$_ENV:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/back-end-$_ENV:latest'
